export enum BookGenres {
  Romance = 'Romance',
  NewRomance = 'New Romance',
  DarkRomance = 'Dark Romance',
  Roman = 'Roman',
  Drame = 'Drame',
  Thriller = 'Thriller',
  Policier = 'Policier',
  Fantastique = 'Fantastique',
  ScienceFiction = 'Science-fiction',
  Aventure = 'Aventure',
  Horreur = 'Horreur',
  Historique = 'Historique',
  Jeunesse = 'Jeunesse',
  Biographie = 'Biographie',
  Essai = 'Essai',
  Poesie = 'Poésie',
  Utopie = 'Utopie',
  Philosophie = 'Philosophie',
  Spiritualite = 'Spiritualité',
  DeveloppementPersonnel = 'Développement Personnel',
  Mythologie = 'Mythologie',
  Humour = 'Humour',
  Comedie = 'Comédie',
  Sport = 'Sport',
  YoungAdult = 'Young Adult',
  BandeDessinee = 'Bande Dessinée',
}
