export enum VideoGameGenres {
  Action = 'Action',
  Aventure = 'Aventure',
  RPG = 'RPG',
  FPS = 'FPS',
  TPS = 'TPS',
  Simulation = 'Simulation',
  Sport = 'Sport',
  Course = 'Course',
  Strategie = 'Stratégie',
  Puzzle = 'Puzzle',
  Survie = 'Survie',
  Horror = 'Horreur',
  BacASable = 'Bac à sable',
  MMO = 'MMO',
  MultijoueursLocal = 'Multijoueurs Local',
  Cooperation = 'Coopération',
}
